### ISSUE TITLE
Div ld_week_browser_buttons goes missing when using prev-next buttons

### ISSUE THREAD

**Issue by mjlassila** [Seravo/Library-Directory#4]
When using widget style 6 (eg. opening hours with previous and next buttons), div#ld_week_browser_buttons goes missing when clicking prev-next -buttons. Example at: https://kirjasto.preview.jyu.fi

**Comment by serter** [comment]
Example url gives 403 error.

**Comment by mjlassila** [comment]
Oops, sorry. The widget without our CSS modifications is here: 
http://minerva.lib.jyu.fi/tmp/libdir-widget-bug.html

**Comment by serter** [comment]
Finally fixed, sorry about the insane delay.
