### ISSUE TITLE
Closed/Open text as configurable feature in the opening hours widget

### ISSUE THREAD

**Issue by mjlassila** [Seravo/Library-Directory#6]
As it seems that closed/open text has been removed intentionally from the opening hours widget (https://github.com/Seravo/Library-Directory/commit/df8810), it would be good to have them back as a configurable feature.  Optionally by default they could have CSS visibility:hidden feature but still be available in the widget.

**Comment by serter** [comment]
Using css visibility would make the content invisible, but still allocate space in the layout.
Maybe use display: none instead?

**Comment by mjlassila** [comment]
Yep, display:none would be the best alternative. Thanks.

**Comment by mjlassila** [comment]
Any news regarding this?

**Comment by serter** [comment]
Sorry, I thought I already had committed the change.

Make status visible with: div.ld_open_now { display: block !important; }
